config/routes.rb
Rails.application.routes.draw do

  domain = Rails.application.config_for(:domain)
  constraints(host: 'www.' + domain) do
    match '/(*path)', to: 'services#www', via: [:get, :post]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  put '/user/:id', to: 'users#update'
  get '/tension', to: 'services#tension'
  
  resources :stocks, only: [:index, :show]
  resources :companies, only: [:index, :show]

  root :to => 'services#index'
  # no routes handler
  match '*path', to: 'services#noroutes', via: [:get, :post]
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_current_user
  before_action :authenticate_user!

  def index

  end

  def tension
    
  end

  def testview
    
  end

  ### incorrect URL handler
  def www
    redirect_to path_without_www, status: 301
  end
  def noroutes
    redirect_to root_path
  end
  ###

  private

  def set_current_user

    return current_user if current_user

    @user = get_user_if_cookies(cookies[:show_me_who_u_r])
    new_cookie = set_new_cookies(:show_me_who_u_r, request.remote_ip)

    if @user
      @user.update_attribute(:show_me_who_u_r, new_cookie)
    else
      @user = User.new(
        :nickname => "guest", 
        :email => "guest_#{Time.now.to_i}#{rand(99)}@guest.tw",  # .tw 可以加入國籍辨別
        :role => "guest",
        :show_me_who_u_r => new_cookie
      )
      @user.save(:validate => false)
    end
    sign_in(@user)
  end

  def get_user_if_cookies(cookie)
    User.find_by_show_me_who_u_r(cookie) if cookie
  end

  def set_new_cookies(cookie, data)
    cookies[cookie] = {
      :value => new_SHA2(data),
      :expires => 1.month.from_now,
    }
    cookies[cookie]
  end

  def new_SHA2(ref)
    require 'digest'
    ref = ref.to_s
    Digest::SHA2.hexdigest ref + Time.now.to_s
  end

  def path_without_www
    domain = dev? ? 'http://localhost:3000' : 'https://' + Rails.application.config_for(:domain)
    domain + request.path
  end
  def dev?
    Rails.env == 'development'
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/index/_contactme.html.erb
<section id="contactme" class="hidden">
  <div class="text-center section-padding">
    <span class="section-title"><%= t('index.contactme') %></span>
  </div>
<!-- 新的資料收集頁面，對我感興趣...!? -->
  <%# form_for @message, url: messages_path do |f| %>

      <%# f.label :user_nickname, "特徵：" %>
      <%# f.text_field :user_nickname,:placeholder => "請輸入您的稱呼", :class => "form-control" %>
    <div class="form-group">
      <label>Name</label>
      <input class="theme_inputbox" type="text" name="Name" required>
       <!-- :hover {border: #000} -->
    </div>
    <div class="form-group">
      <label>Email</label>
      <input class="theme_inputbox" type="text" name="Email" required>
    </div>
    <div class="form-group">
      <label>Subject</label>
      <input class="theme_inputbox" name="Subject" required>
    </div>
    <div class="form-group">
      <label>Message</label>
      <input class="theme_inputbox" name="Message" required>
    </div>

    <div class="pull-right" style="width: 10vw;">
      <button class="theme-btn color-set1 trigger-hidden">Hide</button>
      <%# f.submit "確認" %>
    </div>

    <div style="width: 30vw; margin: 0 auto;">
      <button type="submit" class="theme-btn color-set4">Send</button>
      <%# f.submit "確認" %>
    </div>

  <%# end %>
</section>

app/views/services/index/_mywork.html.erb
<div class="w3-row-padding w3-padding-64 color-set2" id="work" style="margin: 50px;">
  <div class="w3-quarter">
    <h2>Our Work</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

  <div class="w3-quarter">
    <div class="w3-card-2 w3-white">
      <img src="/w3images/fjords.jpg" alt="Vernazza" style="width:100%">
      <div class="w3-container">
        <h3>Customer 1</h3>
        <h4>Trade</h4>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
      </div>
    </div>
  </div>

  <div class="w3-quarter">
    <div class="w3-card-2 w3-white">
      <img src="/w3images/lights.jpg" alt="Cinque Terre" style="width:100%">
      <div class="w3-container">
        <h3>Customer 2</h3>
        <h4>Trade</h4>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
      </div>
    </div>
  </div>

  <div class="w3-quarter">
    <div class="w3-card-2 w3-white">
      <img src="/w3images/mountains.jpg" alt="Monterosso" style="width:100%">
      <div class="w3-container">
        <h3>Customer 3</h3>
        <h4>Trade</h4>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
        <p>Blablabla</p>
      </div>
    </div>
  </div>
</div>

app/views/services/index/_plan_box.html.erb
<div class="col-lg-4">
  <ul class="w3-ul w3-border w3-center w3-hover-shadow">
    <li class="<%= label_color %> w3-xlarge w3-padding-32"><%= level %></li>
    <li class="w3-padding-16"><b><%= unit * 5 %>GB</b> Storage</li>
    <li class="w3-padding-16"><b><%= unit * 5 %></b> Emails</li>
    <li class="w3-padding-16"><b><%= unit * 5 %></b> Domains</li>
    <li class="w3-padding-16"><b><%= warranty %></b> Support</li>
    <li class="w3-padding-16">
      <h2 class="w3-wide">$ <%= unit * 5 %></h2>
      <span class="w3-opacity">per month</span>
    </li>
    <li class="w3-light-grey w3-padding-24">
      <button class="w3-button w3-green w3-padding-large">Sign Up</button>
    </li>
  </ul>
</div>

app/views/services/index/_services.html.erb
<section id="services">
  <div class="clearfix">
    <div class="text-center section-padding">
      <span class="section-title"><%= t('index.What\'s in Here') %></span>
    </div>
    <div class="services-box color-set1">
      <h3><%= link_to t('index.services.tool1.title'), '/tension', method: 'get' %></h3>
      <p><%= t('index.services.tool1.intro') %></p>
    </div>
    <div class="services-box color-set2">
      <h3><%= link_to t('index.services.tool2.title'), stocks_path, method: 'get' %></h3>
      <p><%= t('index.services.tool2.intro') %></p>
    </div>
    <div class="services-box color-set3">
      <h3><%= t('index.services.comingsoon') %></h3>
      <p><%= t('index.services.comingsoon') %></p>
    </div>
    <div class="services-box color-set4">
      <h3><%= t('index.services.comingsoon') %></h3>
      <p><%= t('index.services.comingsoon') %></p>
    </div>
  </div>
</section>

app/views/services/index/_slide_pic.html.erb
<div class="slides">
  <%= image_tag '/index/slider_lessial_' + pic_number + '.jpg' %>
  <div class=<%= position %>>
    <span class="slider-tag color-set0"><%= t('index.slides.' + pic_number ) %></span>
  </div>
</div>

app/views/services/index/_slideshow.html.erb
<section id="slideshow">
  <%= render partial: "/services/index/slide_pic", locals: {pic_number: '1', position: 'topleft'} %>
  <%= render partial: "/services/index/slide_pic", locals: {pic_number: '2', position: 'topmiddle'} %>
  <%= render partial: "/services/index/slide_pic", locals: {pic_number: '3', position: 'topright'} %>
  <!-- Slideshow next/previous buttons -->
  <div class="slider-ctrl color-set3">
    <div class="pull-left" onclick="plusDivs(-1)"><i class="fa fa-arrow-circle-left"></i></div>
    <div class="pull-right" onclick="plusDivs(1)"><i class="fa fa-arrow-circle-right"></i></div>
  
    <div class="text-center">
      <span class="indicator" onclick="currentDiv(1)"></span>
      <span class="indicator" onclick="currentDiv(2)"></span>
      <span class="indicator" onclick="currentDiv(3)"></span>
    </div>
  </div>
</section>

app/views/services/index/_supportme.html.erb
<section id="supportme">
  <div class="text-center section-padding">
    <h3>Pricing Plans</h3>
    <p>Choose a pricing plan that fits your needs.</p>
  </div>
  <%= render partial: "/services/index/plan_box", 
    locals: {label_color: 'color-set4', level: 'Basic', unit: 2, warranty: 'end less'} %>
  <%= render partial: "/services/index/plan_box", 
    locals: {label_color: 'color-set3',level: 'Pro', unit: 5, warranty: 'end less'} %>
  <%= render partial: "/services/index/plan_box", 
    locals: {label_color: 'color-set4',level: 'Premium', unit: 10, warranty: 'end less'} %>
</section>

app/views/services/index/_whoami.html.erb
<section class="clearfix" id="whoami" >
  <div class="text-center section-padding">
    <span class="section-title"><%= t('index.who am i') %></span>
  </div>

  <div class="col-lg-4 col-lg-offset-4">
    <div class="shadowbox">
      <img src="/index/profile.jpg" alt="EJ">
      <div class="theme-container">
        <h3>E.J. Lin</h3>
        <p style="opacity: .6;">Self Engineering</p>
        <p><%= t('index.profile.intro') %></p>
<!--         <p>
          <a class="theme-btn page-scroll color-set3" href="#contactme"><%# t('nav.contactme') %></a>
        </p> -->
      </div>
    </div>
  </div>
</section>